Studee/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
import authentication.views as views


urlpatterns = [
    path('', include('authentication.urls', namespace='authentication')),
    path('admin/', admin.site.urls),
    path('forum/', include('forum.urls', namespace='forum')),
    path('scheduler/', include('scheduler.urls', namespace='scheduler')),
    path('assignments/', include('assignments.urls', namespace='assignments')),
    path('courses/', include('courses.urls', namespace='courses')),
    path('clubs/', include('clubs.urls', namespace='clubs')),
    path('tinymce/', include('tinymce.urls')),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),
    path('account_settings/', views.accountSettings, name='account_settings'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='authentication/changePassword.html'),
         name='password_change'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_change.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    path('password_change/done/', views.password_change_done, name='password_change_done'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
from django.urls import path
from . import views
from .views import *


app_name = "authentication"

urlpatterns = [
    path('home/', views.homePage, name='home'),
    path('', views.landingPage, name='landing'),
    path('register/', views.register, name='register'),
    path('accounts/login/', views.loginView, name='login'),
    path('profile/', views.profile, name='profile'),
    path('editProfile/', views.editProfile, name='editProfile'),
    path('logout/', views.logout_view, name='logout'),
    path('deleteuser/', views.deleteuser, name='deleteuser')
]

clubs/urls.py
from django.http import request
from django.urls import path
from django.conf.urls import url
from .views import *

app_name = "clubs"

urlpatterns = [
    path("", home, name="home"),
    url(r"create_event/(?P<slug>[\w-]+)/$", create_event, name="create_event"),
    url(r"(?P<slug>[\w-]+)/$", club_view, name="club"),
    path("create_club", create_club, name="create_club"),
    path("approve_member", approve_member, name="approve_member"),
]

#handler404 = 'main.views.error404'

authentication/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models
from tinymce.models import HTMLField
import os


class AccountManager(BaseUserManager):
    def create_user(self, username, firstname, lastname, type='Student', password=None):
        from scheduler.models import Preference

        user = self.model(
            username=self.normalize_email(username),
            email=self.normalize_email(username),
            firstname=firstname,
            lastname=lastname,
            type=type
        )

        user.set_password(password)
        user.save(using=self._db)
        vax = Preference(user=user)
        vax.save()
        return user

    def create_superuser(self, username, firstname, lastname, password):
        user = self.create_user(
            username=self.normalize_email(username),
            firstname=firstname,
            lastname=lastname,
            password=password,
            type='Teacher'
        )

        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


def get_filename(instance, filename):
    return os.path.join('authentication/profile_photos', f"{instance.username}.{filename.split('.')[-1]}")


class Account(AbstractBaseUser):
    username = models.EmailField(verbose_name="email", max_length=60, primary_key=True)
    email = models.EmailField(verbose_name="email", max_length=60, null=True, blank=True)
    rn = models.CharField(max_length=10, null=True, blank=True)
    firstname = models.CharField(max_length=30)
    lastname = models.CharField(max_length=30)
    bio = HTMLField(max_length=100, default='', null=True, blank=True)
    forum_credits = models.FloatField(default=0.0)
    assignment_credits = models.IntegerField(default=0)
    profile_pic = models.ImageField(upload_to=get_filename, default="authentication/profile_photos/default.png")
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    type = models.CharField(default='Student', max_length=7, choices=[("Student", "Student"), ("Teacher", "Teacher")])
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['firstname', 'lastname']

    objects = AccountManager()

    def __str__(self):
        return self.firstname + ' ' + self.lastname
    
    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

    def num_posts(self):
        from forum.models import Post
        return Post.objects.filter(user=self).count()

    def submission_rate(self):
        from assignments.models import Assignment, AssignmentSubmission
        assignments = Assignment.objects.count()
        submissions = AssignmentSubmission.objects.filter(user__username=self.username).values_list('assignment__id', flat=True).distinct().count()
        return int(submissions * 100 / assignments) if assignments != 0 else 0

    def get_clubs(self):
        from clubs.models import Members
        clubs = list(Members.objects.filter(member__username=self.username).values_list('club__slug', flat=True))
        approvals = list(Members.objects.filter(member__username=self.username, approved=False).values_list('club__slug', flat=True))
        return {'clubs': clubs, 'approvals': approvals}

    @property
    def course_credits(self):
        from courses.models import EnrolledCourse
        return sum(list(EnrolledCourse.objects.filter(student__username=self.username).values_list('course__credits', flat=True)))

    @property
    def enrolled_courses(self):
        from courses.models import EnrolledCourse
        return list(EnrolledCourse.objects.filter(student__username=self.username).values_list('course__id', flat=True))

    @property
    def points(self):
        return int(self.forum_credits + self.assignment_credits + self.course_credits + self.club_credits)

    @property
    def tier_points(self):
        return [20, 25, 30, 40, 50, 75, 100, 1000]

    @property
    def tier(self):
        tier = 0
        for i, point in enumerate(self.tier_points):
            if self.points < point:
                tier = i
                break
        return tier

    @property
    def points_to_tier(self):
        points_to_tier = 20
        for i, point in enumerate(self.tier_points):
            if self.points < point:
                points_to_tier = point - self.points
                break
        return points_to_tier

    @property
    def tier_image(self):
        return 'tier_' + str(self.tier) + '.png'

    @property
    def vaccination(self):
        from scheduler.models import Preference
        return Preference.objects.get(user_id=self.username)

    @property
    def club_credits(self):
        from clubs.models import Members, Club
        club = len(list(Members.objects.filter(member__username=self.username).values_list('club__slug', flat=True)))
        head = len(list(Club.objects.filter(head__username=self.username).values_list('slug', flat=True)))
        event = len(self.attended_events) * 0.5
        return club + head + event

    @property
    def club_approvals(self):
        from clubs.models import Members
        return Members.objects.filter(approved=False).all()

    @property
    def attended_events(self):
        from clubs.models import EventAttendees
        return list(EventAttendees.objects.filter(attendee__username=self.username).values_list('event__id', flat=True))

authentication/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm

from .models import Account


class AccountAuthenticateForm(forms.ModelForm):
    username = forms.CharField(
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter Email ID'})
    )
    password = forms.CharField(
        label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter Password'})
    )
    class Meta:
        model = Account
        fields = ('username', 'password')

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        if not authenticate(username=username, password=password):
            raise forms.ValidationError("Invalid Login")


# REGISTRATION FORM
class RegistrationForm(UserCreationForm):
    # email = forms.EmailField(max_length=60, help_text='Required. Add a valid email address')

    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter password'}))
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Re-enter password'}))
    type = forms.ChoiceField(
        choices=[("Teacher", "Teacher"), ('Student', 'student')],
        widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Account
        fields = ("username", "firstname", "lastname", "password1", "type")

        widgets = {
            'username': forms.EmailInput(attrs={'class': 'form-control'}),
            'firstname': forms.TextInput(attrs={'class': 'form-control'}),
            'lastname': forms.TextInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
        }


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ("profile_pic", "bio")

        widgets = {
            'bio': forms.Textarea(attrs={'class': 'form-control'})
        }

authentication/views.py
from django import template
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.template import loader
from django.db.models import Max
import json

from .forms import *
from .models import Account
from courses.models import Course
from forum.models import Post
from django.http import HttpResponse
from clubs.models import Club, Events
from scheduler.models import Preference

# Display landing page 
def landingPage(request):
    if request.user.is_authenticated:
        return redirect("authentication:home")
    return render(request, 'landing.html')

# Display home dashboard once logged in
@login_required
def homePage(request):
    events = list(Events.objects.values().all())
    event_data = get_events(events)
    template = loader.get_template('home.html')

    tiers = []
    perks = ['Coffee', 'Cookie', 'Popcorn', 'Ice Cream', 'Donut', 'Burger', 'Meal']
    for i in range(7):
        tiers.append(
            {
                'value': i,
                'image': 'tier_' + str(i) + '.png',
                'points_to_next': request.user.tier_points[i] - request.user.points,
                'perk': perks[i]
            }
        )
    credit_data = [request.user.assignment_credits, request.user.forum_credits, request.user.club_credits, request.user.course_credits]
    credit_stars = Account.objects.filter(username__in=get_credit_star()).all()
    if request.user.vaccination.vaccination_status != 'Fully Vaccinated':
        messages.warning(request, f'Get fully vaccinated in order to attend offline classes or join clubs')
    context = {
        'event_data': event_data,
        'tiers': tiers,
        'credit_data': json.dumps(credit_data),
        'credit_stars': credit_stars
    }
    return HttpResponse(template.render(context, request))

# Sign up
def register(request):
    context = {}
    if request.POST:
        form = RegistrationForm(request.POST)

        if (request.method == 'POST') and (form.is_valid()):
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            account = authenticate(username=username, password=raw_password)
            login(request, account)
            user = Account.objects.get(username=username)
            preference = Preference(user=user)
            if user.type == 'Teacher':
                preference.vaccination_status = 'Fully Vaccinated'
            preference.save()
            messages.success(request, f'Your account has been created successfully!')

            return redirect('authentication:home')
        else:
            context['registration_form'] = form
    else:
        form = RegistrationForm()
        context['registration_form'] = form
    return render(request, 'authentication/register.html', context)

# Sign in
def loginView(request):
    context = {}
    if request.user.is_authenticated:
        return redirect("authentication:home")
    if request.POST:
        form = AccountAuthenticateForm(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect("authentication:home")
    else:
        form = AccountAuthenticateForm()
    if form.non_field_errors():
        messages.error(request, f'The username or password you entered is incorrect. Please try again.')

    context['login_form'] = form
    return render(request, 'authentication/login.html', context)

# Log out
def logout_view(request):
    logout(request)
    return redirect('authentication:landing')

# Display events calendar on home dashboard
def get_events(events):
    event_list = []
    for event in events:
        club = Club.objects.get(slug=event['club_id']).name
        event_list.append({
            'name': event['name'],
            'description': event['description'],
            'club': club,
            'year': event['date'].year,
            'month': event['date'].month,
            'day': event['date'].day,
            'hour': event['date'].hour,
            'minute': event['date'].minute,
            'duration': event['duration'],
        })
    return {
        'events': event_list
    }

# User profile page
@login_required
def profile(request):
    template = loader.get_template('authentication/profile.html')
    profile_form = ProfileUpdateForm(instance=Account.objects.get(username=request.user.username))
    context = {
        'profile_form': profile_form
    }
    return HttpResponse(template.render(context, request))

# Edit profile
@login_required
def editProfile(request):
    template = loader.get_template("authentication/editProfile.html")
    if request.method == 'POST':
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=Account.objects.get(username=request.user.username))
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, f'Your account has been updated successfully!')
            return redirect('authentication:profile')
    else:
        profile_form = ProfileUpdateForm(instance=Account.objects.get(username=request.user.username))

    context = {
        'profile_form': profile_form
    }
    return HttpResponse(template.render(context, request))

# Delete user
def deleteuser(request):
    if request.method == 'POST':
        Account.objects.filter(username=request.user.username).delete()
        messages.success(request, 'Your account has been deleted. To create a new account, register here!')
        return redirect('authentication:register')
    else:
        template = loader.get_template("authentication/deleteAccount.html")
        context = {}
        return HttpResponse(template.render(context, request))

# User settings
@login_required
def accountSettings(request):
    template = loader.get_template("authentication/accountSettings.html")
    context = {}
    return HttpResponse(template.render(context, request))

# Change password
@login_required
def password_change_done(request):
    messages.success(request, f'Your account has been updated successfully!')
    return redirect('account_settings')

# Display tar student with highest credits
def get_credit_star():
    max_credits = 0
    credit_stars = []
    users = Account.objects.filter(type='Student').all()
    for user in users:
        if user.points > max_credits:
            max_credits = user.points

    for user in users:
        if user.points == max_credits:
            credit_stars.append(user.username)
    return credit_stars

authentication/templates/authentication/accountSettings.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Home
{% endblock %}
{% block content %}
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div style="color:red;">
                    {{ message|safe }}
                </div>
            {% else %}
                <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">
                    {{ message|safe }}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">
            Account Settings
        </h1>
    </div>

    <!-- Content Row -->
    <div class="row">
        <!-- Change Password Card -->
        <a class="col-xl-3 col-md-6 mb-4" href="{% url 'password_change' %}">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-sm font-weight-bold text-warning text-uppercase mb-1">
                                Change Password</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-solid fa-lock fa-2x text-warning"></i>
                        </div>
                    </div>
                </div>
            </div>
        </a>

        <!-- Delete Account Card -->
        <a class="col-xl-3 col-md-6 mb-4" href="{% url 'authentication:deleteuser' %}">
            <div class="card border-left-danger shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-sm font-weight-bold text-danger text-uppercase mb-1">
                                Delete Account
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-solid fa-ban fa-2x text-danger"></i>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    </div>
{% endblock %}

authentication/templates/authentication/changePassword.html
{% extends 'base.html' %}
{% block title %}
    Delete Account
{% endblock %}
{% block content %}
    <a class="h6 mb-5 text-gray-800" href="{% url 'account_settings' %}">
        Account Settings
    </a>
    <i class="fa fa-angle-right fa-sm text-primary mx-1"></i>
    <div class="d-sm-flex align-items-center justify-content-between mb-4 mt-3">
        <h1 class="h3 mb-0 text-gray-800">
            Change Password
        </h1>
    </div>
    <div class="col-md-6" id="panel">
        {% for field in form %}
            {% for error in field.errors %}
                <p style="color:red;">
                    {{error}}
                </p>
            {% endfor %}
        {% endfor %}
        {% if form.non_field_errors %}
            {{ form.non_field_errors }}
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="userpassword">
                    Old Password
                </label>
                <div class="input-group mb-3">
                    <input name="old_password" class="form-control" type="password" id="id_old_password" placeholder="Old Password" required="true">
                </div>
            </div>
            <!-- end of form group -->
            <div class="form-group">
                <label for="userpassword">
                    New Password
                </label>
                <div class="input-group mb-3">
                    <input name="new_password1" class="form-control" type="password" id="id_new_password1" placeholder="New Password" required="true">
                </div>
            </div>
            <!-- end of form group -->
            <div class="form-group">
                <label for="userpassword">
                    Re-enter Password
                </label>
                <div class="input-group mb-3">
                    <input name="new_password2" class="form-control" type="password" id="id_new_password2" placeholder="Confirm Password" required="true">
                </div>
            </div>
            <!-- end of form group -->
            <div class="row justify-content-around mt-5">
                <div class="col-md-4">
                    <a href="{% url 'account_settings' %}" class="btn btn-outline-primary btn-block waves-effect waves-light">
                        Cancel
                    </a>
                </div>
                <div class="col-md-4">
                    <button class="btn btn-primary btn-block waves-effect waves-light" type="submit">
                        Save
                    </button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

authentication/templates/authentication/deleteAccount.html
{% extends 'base.html' %}
{% block title %}
    Delete Account
{% endblock %}
{% block content %}
    <a class="h6 mb-5 text-gray-800" href="{% url 'account_settings' %}">
        Account Settings
    </a>
    <i class="fa fa-angle-right fa-sm text-primary mx-1"></i>
    <div class="d-sm-flex align-items-center justify-content-between mb-4 mt-3">
        <h1 class="h3 mb-0 text-gray-800">
            Delete Account
        </h1>
    </div>
    <div id="deleteAccountPanel" class="col-md-10">
        <p class="delete-account">
            Delete your account and your account data
        </p>
        <form action="" method="post">
            {% csrf_token %}
            <button class="btn btn-outline-danger btn-block waves-effect waves-light col-md-2" type="submit" name="delete-account">
                Delete
            </button>
        </form>
    </div>
{% endblock %}

authentication/templates/authentication/editProfile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Edit Profile
{% endblock %}
{% block content %}
    <link href="{% static 'css/app.css'%}" rel="stylesheet" type="text/css" />
    <div class="row col-md-10 mx-auto ">
        <div class="container-fluid my-5">
            <form method="POST" enctype="multipart/form-data" >
                {% csrf_token %}
                {% include 'authentication/profileCard.html' %}
            </form>
        </div>
    </div>
{% endblock %}

authentication/templates/authentication/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Profile
{% endblock %}
{% block content %}
    <link href="{% static 'css/app.css'%}" rel="stylesheet" type="text/css" />
    <div class="row col-md-10 mx-auto ">
        <div class="container-fluid mt-5">
            {% include 'authentication/profileCard.html' %}
        </div>
    </div>

{% endblock %}

authentication/templates/authentication/profileCard.html
<div class="card shadow-sm profile-card py-5">
    {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
        {% endfor %}
    {% endif %}
    {% for field in profile_form %}
        {% for error in field.errors %}
            <p style="color:red;">{{error}}</p>
        {% endfor %}
    {% endfor %}
    <div class="row">
        <div class="col-lg-2 user-image-class">
            {% if request.get_full_path == '/editProfile/' %}
                <label for="imageId" class="rounded-circle image">
                    <img src="{{request.user.profile_pic.url}}" id="img" class="rounded-circle user-image-edit" alt="profile_photo"/>
                    <div class="edit-photo">
                        <i class="fa fa-camera edit-photo-icon "></i>
                    </div>
                </label>
                <input type="file" style="display: none" name="profile_pic" id="imageId" class="user-image-edit">
            {% else %}
                <img src="{{request.user.profile_pic.url}}" class="rounded-circle user-image"/>
            {% endif %}
        </div>
        <div class="col-lg-10 user-information">
            <p class="header">
                {{request.user|title}}
                <a href="{% url 'authentication:editProfile' %}" style="text-decoration: none">
                    {% if request.get_full_path == '/profile/' %}
                        <i class="fa fa-pen profile-button fa-xs mx-2"></i>
                    {% endif %}
                </a>
            </p>
            <p>{{ request.user.type }}</p>
        </div>
    </div>
    {% include 'authentication/profileData.html' %}
</div>

<script>
    $(function(){
        $('#imageId').change(function(){
            var input = this;
            var url = $(this).val();
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#img').attr('src', e.target.result);
            };
            reader.readAsDataURL(input.files[0]);
        });
    });
</script>

authentication/templates/authentication/register.html
{% extends 'authentication/loginBase.html' %}
{#{% load static %}#}
{% block content %}
    <div class="card col-6 align-self-center">
        <div class="col-10 my-5 align-self-center">
            <h2>
                Create an Account
            </h2>
            <form method="POST">
                {% csrf_token %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">
                            {{ message|safe }}
                        </div>
                    {% endfor %}
                {% endif %}
                {% if registration_form.non_field_errors %}
                    {{ registration_form.non_field_errors }}
                {% endif %}
                <hr>
                <div class="form-group">
                    <label for="username">
                        Email ID
                    </label>
                    <p>
                        {{ registration_form.username }}
                    </p>
                    {% for error in registration_form.username.errors %}
                        <p style="color:red;">
                            {{error}}
                        </p>
                    {% endfor %}
                </div>
                <!--end form-group-->
                <div class="form-group">
                    <label for="firstname">
                        First Name
                    </label>
                    <p>
                        {{ registration_form.firstname }}
                    </p>
                    {% for error in registration_form.firstname.errors %}
                        <p style="color:red;">
                            {{error}}
                        </p>
                    {% endfor %}
                </div>
                <!--end form-group-->
                <div class="form-group">
                    <label for="lastname">
                        Last Name
                    </label>
                    <p>
                        {{ registration_form.lastname }}
                    </p>
                    {% for error in registration_form.lastname.errors %}
                        <p style="color:red;">
                            {{error}}
                        </p>
                    {% endfor %}
                </div>
                <!--end form-group-->
                <div class="form-group">
                    <label for="type">
                        User Type
                    </label>
                    <p>
                        {{ registration_form.type }}
                    </p>
                    {% for error in registration_form.type.errors %}
                        <p style="color:red;">
                            {{error}}
                        </p>
                    {% endfor %}
                </div>
                <!--end form-group-->
                <div class="form-group">
                    <label for="userpassword">
                        Password
                    </label>
                    <p>
                        {{ registration_form.password1}}
                    </p>
                    {% for error in registration_form.password2.errors %}
                        <p style="color:red;">
                            {{error}}
                        </p>
                    {% endfor %}
                    <p>
                        {{ registration_form.password2}}
                    </p>
                </div>
                <!--end form-group-->
                <div class="form-group mb-0 row">
                    <div class="col-12 mt-2">
                        <button class="btn btn-primary  btn-block waves-effect waves-light" type="submit">
                            Create Account
                        </button>
                    </div>
                </div>
                <!--end form-group-->
                <h6 style="text-align:center">
                    Already have an account?
                    <a href="{% url 'authentication:login' %}" class="text-primary">
                        Sign In
                    </a>
                </h6>
            </form>
        </div>
    </div>
{% endblock %}