Studee/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
import authentication.views as views


urlpatterns = [
    path('', include('authentication.urls', namespace='authentication')),
    path('admin/', admin.site.urls),
    path('forum/', include('forum.urls', namespace='forum')),
    path('scheduler/', include('scheduler.urls', namespace='scheduler')),
    path('assignments/', include('assignments.urls', namespace='assignments')),
    path('courses/', include('courses.urls', namespace='courses')),
    path('clubs/', include('clubs.urls', namespace='clubs')),
    path('tinymce/', include('tinymce.urls')),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),
    path('account_settings/', views.accountSettings, name='account_settings'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='authentication/changePassword.html'),
         name='password_change'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_change.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    path('password_change/done/', views.password_change_done, name='password_change_done'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
from django.urls import path
from . import views
from .views import *


app_name = "authentication"

urlpatterns = [
    path('home/', views.homePage, name='home'),
    path('', views.landingPage, name='landing'),
    path('register/', views.register, name='register'),
    path('accounts/login/', views.loginView, name='login'),
    path('profile/', views.profile, name='profile'),
    path('editProfile/', views.editProfile, name='editProfile'),
    path('logout/', views.logout_view, name='logout'),
    path('deleteuser/', views.deleteuser, name='deleteuser')
]

clubs/urls.py
from django.http import request
from django.urls import path
from django.conf.urls import url
from .views import *

app_name = "clubs"

urlpatterns = [
    path("", home, name="home"),
    url(r"create_event/(?P<slug>[\w-]+)/$", create_event, name="create_event"),
    url(r"(?P<slug>[\w-]+)/$", club_view, name="club"),
    path("create_club", create_club, name="create_club"),
    path("approve_member", approve_member, name="approve_member"),
]

#handler404 = 'main.views.error404'

forum/urls.py
from django.urls import path
from django.conf.urls import url
from .views import *

app_name = "forum"

urlpatterns = [
    path("", home, name="home"),
    url(r"detail/(?P<slug>[-\w]+)/$", detail, name="detail"),
    url(r"posts/(?P<slug>[\w-]+)/$", posts, name="posts"),
    path("create_post", create_post, name="create_post"),
    # path("latest_posts", latest_posts, name="latest_posts"),
]

forum/models.py
from django.db import models
from django.utils.text import slugify
from authentication.models import Account
from tinymce.models import HTMLField
from hitcount.models import HitCount
from django.contrib.contenttypes.fields import GenericRelation
from django.shortcuts import reverse


class Category(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=400, unique=True, blank=True)
    description = models.TextField(default="description")

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Category, self).save(*args, **kwargs)

    @property
    def num_posts(self):
        return Post.objects.filter(categories=self).count()
    
    @property
    def last_post(self):
        return Post.objects.filter(categories=self).latest("date")


class Post(models.Model):
    title = models.CharField(max_length=400)
    slug = models.SlugField(max_length=400, unique=True, blank=True)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    content = HTMLField()
    categories = models.ForeignKey(Category, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk', related_query_name='hit_count_generic_relation')
    tags = models.TextField(blank=True)
    closed = models.BooleanField(default=False)
    state = models.CharField(max_length=40, default="zero")

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    @property
    def last_reply(self):
        return Comment.objects.filter(post=self).latest('date')

    @property
    def num_comments(self):
        return Comment.objects.filter(post=self).count()

    @property
    def get_tags(self):
        return self.tags.split(',')


class Comment(models.Model):
    id = models.AutoField(primary_key=True, unique=True)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def replies(self):
        return Reply.objects.filter(comment=self).all()


class Reply(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "replies"

forum/forms.py
from django import forms
from .models import Post, Category, Comment, Reply


class PostForm(forms.ModelForm):
    categories = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=False
    )

    class Meta:
        model = Post
        fields = ["title", "content", "categories", "tags"]

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.TextInput(attrs={'class': 'form-control'}),
            'tags': forms.TextInput(attrs={'class': 'form-control'}),
        }


class CategoryForm(forms.ModelForm):
    title = forms.CharField(required=False)
    description = forms.CharField(required=False)

    class Meta:
        model = Category
        fields = ["title", "description"]

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
        }


class CommentForm(forms.ModelForm):
    content = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control', 'type': 'text', 'placeholder': 'Enter your comment here', 'style': 'height:4rem!important'}))

    class Meta:
        model = Comment
        fields = ["content"]


class ReplyForm(forms.ModelForm):
    content = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control', 'type': 'text', 'placeholder': 'Enter your reply here', 'style': 'height:4rem!important'}))

    class Meta:
        model = Reply
        fields = ["content"]

forum/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import *
from .utils import update_views
from .forms import PostForm, CategoryForm, CommentForm, ReplyForm
from django.contrib.auth.decorators import login_required
from django.db.models import F
from django.contrib import messages


def home(request):
    categories = Category.objects.all()
    num_users = Account.objects.all().count()
    num_categories = categories.count()
    num_posts = Post.objects.all().count()
    try:
        last_post = Post.objects.latest("date")
    except:
        last_post = []

    context = {
        "categories": categories,
        "num_users": num_users,
        "num_posts": num_posts,
        "num_categories": num_categories,
        "last_post": last_post,
        "title": "OZONE forum app"
    }
    return render(request, "forum/forums.html", context)


def detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    comments = Comment.objects.filter(post=post).all()
    context = {
        "comments": comments,
        "post": post,
        "title": "OZONE: " + post.title,
    }
    if request.user.is_authenticated:
        if request.method == "POST":
            if 'delete-comment' in request.POST:
                Comment.objects.filter(id=request.POST['delete-comment']).delete()
                messages.success(request, f'Your comment has been deleted')
                return redirect("forum:detail", slug=slug)
            if 'delete-reply' in request.POST:
                Reply.objects.filter(id=request.POST['delete-reply']).delete()
                messages.success(request, f'Your reply has been deleted')
                return redirect("forum:detail", slug=slug)
            if 'delete-post' in request.POST:
                category_slug = Post.objects.filter(slug=request.POST['delete-post']).values('categories__slug')[0]['categories__slug']
                Post.objects.filter(slug=request.POST['delete-post']).delete()
                messages.success(request, f'Your post has been deleted')
                if Post.objects.filter(categories__slug=category_slug).count() == 0:
                    Category.objects.filter(slug=category_slug).delete()
                    return redirect('forum:home')
                return redirect("forum:posts", slug=category_slug)
            comment_form = CommentForm(request.POST, prefix='comment')
            reply_form = ReplyForm(request.POST, prefix='reply')
            author = Account.objects.get(username=request.user.username)
            if (comment_form.is_valid()) and (comment_form['content'].value() is not None):
                new_comment = comment_form.save(commit=False)
                new_comment.user = author
                new_comment.post = post
                new_comment.save()
                update_credits(request, 0.1)
                messages.success(request, f'Your comment has been posted. You have earned 0.1 credits')
                return redirect("forum:detail", slug=slug)
            if (reply_form.is_valid()) and (reply_form['content'].value() is not None):
                new_reply = reply_form.save(commit=False)
                new_reply.user = author
                new_reply.comment = Comment.objects.get(id=request.POST.get('comment_id'))
                new_reply.save()
                update_credits(request, 0.1)
                messages.success(request, f'Your reply has been posted. You have earned 0.1 credits')
                return redirect("forum:detail", slug=slug)
        else:
            comment_form = CommentForm(prefix='comment')
            reply_form = ReplyForm(prefix='reply')
            context = {
                "comment_form": comment_form,
                "reply_form": reply_form,
                "comments": comments,
                "post": post,
                "title": "OZONE: " + post.title,
            }
            update_views(request, post)
            return render(request, "forum/detail.html", context)

    update_views(request, post)
    return render(request, "forum/detail.html", context)


def posts(request, slug):
    if request.method == 'POST':
        Post.objects.filter(slug=request.POST['delete-post']).delete()
        messages.success(request, f'Your post has been deleted')
        if Post.objects.filter(categories__slug=slug).count() == 0:
            Category.objects.filter(slug=slug).delete()
            return redirect('forum:home')
        return redirect('forum:posts', slug=slug)
    else:
        category = Category.objects.get(slug=slug)
        posts = Post.objects.filter(categories=category.id).all()

        context = {
            "posts": posts,
            "forum": category,
            "title": "Studee: Posts"
        }

        return render(request, "forum/posts.html", context)


@login_required
def create_post(request):
    if request.method == "POST":
        post_form = PostForm(request.POST, prefix='post')
        category_form = CategoryForm(request.POST, prefix='category')
        if (category_form.is_valid()) and (post_form['categories'].value() == ''):
            category = category_form.save()
        if post_form.is_valid():
            author = Account.objects.get(username=request.user.username)
            new_post = post_form.save(commit=False)
            new_post.user = author
            if post_form['categories'].value() == '':
                new_post.categories = Category.objects.get(slug=category.slug)
            new_post.save()
            update_credits(request, 0.25)
            messages.success(request, f'Your post has been created. You have earned 0.25 credits')
            return redirect("forum:home")
    else:
        post_form = PostForm(prefix='post')
        category_form = CategoryForm(prefix='category')
        context = {
            "create_form": post_form,
            "cat_form": category_form,
            "title": "Studee: Create New Post"
        }
        return render(request, "forum/create_post.html", context)


# def latest_posts(request):
#     posts = Post.objects.all().filter(approved=True)[:10]
#     context = {
#         "posts": posts,
#         "title": "Studee: Latest 10 Posts"
#     }
#
#     return render(request, "forum/latest_posts.html", context)


def update_credits(request, credits):
    credit_account = Account.objects.get(username=request.user.username)
    credit_account.forum_credits = F('forum_credits') + credits
    credit_account.save()

forum/templates/forum/create_post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %} 
{%load static %}
<style>
  .category-form {
    display: none;
  }
</style>
<a class="h6 mb-5 text-gray-800" href="{% url 'forum:home' %}"> Forum </a>
<i class="fa fa-angle-right fa-sm text-primary mx-1"></i>
<br /><br />
<h1 class="mt-3" style="margin-block: 50px; text-gray-800;">
  Hi {{user.firstname}}, start a discussion!
</h1>
<div class="row">
  <div class="col-md-8">
    <form method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label for="title"> Post Title </label>
        <p>{{ create_form.title }}</p>
        {% for error in create_form.title.errors %}
        <p style="color: red">{{error}}</p>
        {% endfor %}
      </div>
      <!--end form-group-->
      <div class="form-group">
        <label for="content"> Post </label>
        <p>{{ create_form.content }}</p>
        {% for error in create_form.content.errors %}
        <p style="color: red">{{error}}</p>
        {% endfor %}
      </div>
      <!--end form-group-->
      <div class="form-group">
        <label for="categories"> Select from existing category </label>
        <p>{{ create_form.categories }}</p>
        {% for error in create_form.categories.errors %}
        <p style="color: red">{{error}}</p>
        {% endfor %}
        <button onclick="new_category()" type="button" class="btn btn-primary">
          Create a new category
        </button>
        <div class="form-group category-form">
          <label for="title"> Category Title </label>
          <p>{{ cat_form.title }}</p>
          {% for error in cat_form.title.errors %}
          <p style="color: red">{{error}}</p>
          {% endfor %}
        </div>
        <!--end form-group-->
        <div class="form-group category-form">
          <label for="description"> Category Description </label>
          <p>{{ cat_form.description }}</p>
          {% for error in cat_form.description.errors %}
          <p style="color: red">{{error}}</p>
          {% endfor %}
        </div>
        <!--end form-group-->
        <br />
      </div>
      <div class="form-group">
        <label for="tags"> Tags </label>
        <p>{{ create_form.tags }}</p>
        {% for error in create_form.tags.errors %}
        <p style="color: red">{{error}}</p>
        {% endfor %}
      </div>
      <!--end form-group-->
      <div class="form-group mb-0 row">
        <div class="col-12 mt-2">
          <button
            class="btn btn-primary btn-block waves-effect waves-light"
            type="submit"
          >
            Create Post
          </button>
        </div>
        <!--end form-group-->
      </div>
    </form>
  </div>
  <div class="col-xl-4 col-lg-5">
    <div
      class="
        card
        shadow
        py-4
        d-sm-flex
        align-items-center
        justify-content-between
        mb-4
      "
    >
      <h5 class="mx-5 py-3">
        Engagement on the student forum can earn your extra credits!
      </h5>
      <img
        class="card-img-top mx-auto d-block p-5"
        src="{% static 'undraw_social_interaction_re_dyjh1.png' %}"
        alt="an image"
      />
    </div>
  </div>
</div>

<script>
  function new_category() {
    const elements = document.getElementsByClassName("category-form");
    for (var i = 0; i < elements.length; i++)
      elements[i].style.display = "block";
  }
</script>
{% endblock content %}

forum/templates/forum/forum-template.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Studee Forum</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/forum.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Titillium+Web:ital@1&display=swap" rel="stylesheet">
</head>

<body>
    <header>
        <!--NavBar Section-->
        <div class="navbar">
            <nav class="navigation hide" id="navigation">
                <span class="close-icon" id="close-icon" onclick="showIconBar()"><i class="fa fa-close"></i></span>
                <ul class="nav-list">
                    <li class="nav-item"><a href="{% url 'authentication:home' %}">Home</a></li>
                    {% if user.is_authenticated %}
                    <li class="nav-item"><a href="{% url 'authentication:logout' %}">Logout</a></li>
                    {% else %}
                    <li class="nav-item"><a href="{% url 'authentication:register' %}">Signup</a></li>
                    <li class="nav-item"><a href="{% url 'authentication:login' %}">Signin</a></li>
                    {% endif %}
                </ul>
            </nav>
            <a class="bar-icon" id="iconBar" onclick="hideIconBar()"><i class="fa fa-bars"></i></a>
            <div class="brand">Studee</div>
            {% if user.is_authenticated %}
            <div style="font-size:50px;margin-left:100px;"><a href="{% url 'forum:create_post' %}">+</a></div>
            {% endif %}
        </div>
        <!--SearchBox Section-->
                <form action="{% url 'forum:search_result' %}" role="form" method="GET">
                <div class="search-box">
                    <div>
                        <select name="search-box" id="">
                            <option value="Everything">Everything</option>
                            <option value="Titles">Titles</option>
                            <option value="Descriptions">Descriptions</option>
                        </select>
                        <input type="text" name="q" placeholder="search ...">
                        <button type="submit" name="search"><i class="fa fa-search"></i></button>
                    </div>
                </div>
                </form>
    </header>
    {% if messages %}
        {% for message in messages %}
            <div style="background-color:#fff;color:#000;font-weight:bolder;padding:20px;width:100%;"> {{message}} </div>
        {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock content %}
    <div style="margin-bottom: 150px;"></div>
    <footer>
        <span>&copy;  Ishita Datta | All Rights Reserved</span>
    </footer>
    <script src="{% static 'js/main.js' %}"></script>
   
</body>
</html>

forum/templates/forum/forums.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ title }}
{% endblock %}
{% block content %}
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div style="color:red;">
                    {{ message|safe }}
                </div>
            {% else %}
                <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">
                    {{ message|safe }}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">
            Forums
        </h1>
    </div>

    <!-- Content Row -->
    <div class="row">
        <!-- Total Categories Card -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                Total Categories
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-warning-800">{{ num_categories }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-award fa-2x text-warning"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Total Posts Card -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                Total Posts</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ num_posts }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-comments fa-2x text-success"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Engagement score legend card -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">
                                Your Engagement Score
                            </div>
                            <div class="row no-gutters align-items-center">
                                <div class="col-auto">
                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">50%</div>
                                </div>
                                <div class="col">
                                    <div class="progress progress-sm mr-2">
                                        <div class="progress-bar bg-info" role="progressbar"
                                            style="width: 50%" aria-valuenow="{50" aria-valuemin="0"
                                            aria-valuemax="100">

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-clipboard-list fa-2x text-info"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Create a new post button  -->
        <div class="col-xl-3 col-md-6 mb-4">
            <a class="btn btn-primary shadow w-100 h-100" href="{% url 'forum:create_post' %}" style="align-items:center; text-align: center">
                <div class="font-weight-bold text-uppercase p-2 my-auto" style="font-size: 20px; vertical-align: middle">
                    Create new post
                </div>
            </a>
        </div>
    </div>

    <!-- Content Row -->
    <div class="row">
        <!-- Category card -->
        <div class="col-xl-8 col-lg-7">
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-0 text-gray-800">
                    Categories
                </h1>
            </div>
            <!-- Card Header - Dropdown -->
            {% for category in categories %}
                <div class="card shadow mb-4" href="{% url 'forum:posts' category.slug|slugify %}">
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        <h6 class="m-0 font-weight-bold text-primary">
                            <span>
                                {{category.title}}
                            </span>
                        </h6>
                        <a href="{% url 'forum:posts' category.slug|slugify %}" class="btn btn-outline-primary">
                            View Category
                        </a>
                    </div>
                    <!-- Card Body -->
                    <div class="card-body">
                        <p>{{category.description}} </p>
                    </div>
                    <div class="card-footer py-3 d-flex flex-row align-items-center justify-content-between">
                        {% if last_post %}
                            <span>
                                <b><a href="{% url 'forum:detail' last_post.slug|slugify %}">Last post</a></b> by <a href="">{{last_post.user|title}}</a>
                                <br>on <small>{{last_post.date|date}}</small>
                            </span>
                        {% else %}
                            <span>No posts in this category.</span>
                        {% endif %}
                        <span>{{category.num_posts}} Post{{category.num_posts|pluralize}}</span>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="col-xl-4 col-lg-5">
            <div class="card shadow py-4 d-sm-flex align-items-center justify-content-between mb-4">
                <h6 class="col-6 mx-4 my-2 py-3" style="position: absolute; right: 0">
                    Higher engagement on the forum can earn you <b>extra</b> credits
                </h6>
                <img class="card-img-top mx-auto d-block col-11 my-5" src="{% static 'undraw_social_interaction_re_dyjh1.png' %}" alt="an image">
                <div class="col-6 mx-4 my-2 py-3 flex-wrap" style="position: absolute; left: 5%; bottom: 0">
                    <h6><b>Posts</b><br><i class="fas fa-award text-warning"></i>  0.25 credits </h6> 
                    <h6><b>Comments</b><br><i class="fas fa-award text-warning"></i>  0.1 credits </h6>
                    <h6><b>Replies</b><br><i class="fas fa-award text-warning"></i>  0.1 credits </h6>
                </div>
            </div>
        </div>
    </div>
 {% endblock content %}

forum/templates/forum/latest_posts.html
{% extends 'forum/forum-template.html' %}
{% load hitcount_tags %}
{% block content %}
    <div class="container">
        <!--Navigation-->
        <div class="navigate">
            <span>Latest 10 Posts</span>
        </div>
        <!--Display posts table-->
        <div class="posts-table">
            <div class="table-head">
                <div class="status">Status</div>
                <div class="subjects">Subjects</div>
                <div class="replies">Replies/Views</div>
                <div class="last-reply">Last Reply</div>
            </div>

            {% for post in posts %}
            <div class="table-row">
                <div class="status"><i class="fa fa-fire"></i></div>
                <div class="subjects">
                    <a href="{% url 'forum:detail' post.slug|slugify %}">{{post.title}}</a>
                    <br>
                    <span>Started by <b><a href="">{{post.user.fullname|title}}</a></b> .</span>
                </div>
                <div class="replies">
                    {{post.num_comments}} comments <br> {% get_hit_count for post %} views
                </div>

                <div class="last-reply">
                    {{post.last_reply.date|date}}
                    <br>By <b><a href="">{{post.last_reply.user.fullname|title}}</a></b>
                </div>
            </div>
            {% endfor %}

            
        </div>
        </div>

    {% endblock content %}