Studee/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
import authentication.views as views


urlpatterns = [
    path('', include('authentication.urls', namespace='authentication')),
    path('admin/', admin.site.urls),
    path('forum/', include('forum.urls', namespace='forum')),
    path('scheduler/', include('scheduler.urls', namespace='scheduler')),
    path('assignments/', include('assignments.urls', namespace='assignments')),
    path('courses/', include('courses.urls', namespace='courses')),
    path('clubs/', include('clubs.urls', namespace='clubs')),
    path('tinymce/', include('tinymce.urls')),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),
    path('account_settings/', views.accountSettings, name='account_settings'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='authentication/changePassword.html'),
         name='password_change'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_change.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    path('password_change/done/', views.password_change_done, name='password_change_done'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

assignments/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

app_name = "assignments"

urlpatterns = [
    path('create/(?P<id>\w{0,50})/$', AssignmentCreateView, name='create'),
    path('create/', AssignmentCreateView, name='create'),
    path('', AssignmentView, name='home'),
    url(r'submit/(?P<id>\w{0,50})/$', AssignmentSubmissionView, name='submit'),
    url(r'submit-view/(?P<id>\w{0,50})/$', SubmittedAssignment, name='submit-view'),
    path('submission/(?P<id>\w{0,50})/$', AssignmentSubmissionListView, name='submissions'),
]

clubs/urls.py
from django.http import request
from django.urls import path
from django.conf.urls import url
from .views import *

app_name = "clubs"

urlpatterns = [
    path("", home, name="home"),
    url(r"create_event/(?P<slug>[\w-]+)/$", create_event, name="create_event"),
    url(r"(?P<slug>[\w-]+)/$", club_view, name="club"),
    path("create_club", create_club, name="create_club"),
    path("approve_member", approve_member, name="approve_member"),
]

#handler404 = 'main.views.error404'

assignments/models.py
from django.db import models
from authentication.models import Account
from courses.models import Course
from django.utils import timezone
import os


class Assignment(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='Teacher')
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    marks = models.IntegerField()
    deadline = models.DateTimeField(default=timezone.now)
    created_at = models.DateTimeField(default=timezone.now)


def get_filename(instance, filename):
    return os.path.join('assignments', f"{instance.user.username}_Assignment{instance.assignment.id}.{filename.split('.')[-1]}")


class AssignmentSubmission(models.Model):
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    file = models.FileField(null=True, blank=True, upload_to=get_filename)
    marks = models.IntegerField(blank=True, null=True)

assignments/forms.py
from django import forms
from .models import Assignment, AssignmentSubmission
from courses.models import Course
from authentication.models import Account


# Create assignment form
class AssignmentCreateForm(forms.ModelForm):
    course = forms.ModelChoiceField(
        queryset=Course.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control', }),
    )
    deadline = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'class': "form-control", "type": "date"}))

    class Meta:
        model = Assignment
        fields = ("title", "content", "course", "marks", "deadline")

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.TextInput(attrs={'class': 'form-control'}),
            'marks': forms.NumberInput(attrs={'class': 'form-control'}),
        }


# Assignment Submission Form
class AssignmentSubmissionForm(forms.ModelForm):
    class Meta:
        model = AssignmentSubmission
        fields = ("file", )

        widgets = {
            'file': forms.FileInput(attrs={'class': 'custom-file-input'}),
        }

assignments/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.template import loader
from django.contrib import messages
from django.shortcuts import redirect
import os
import json
from django.conf import settings
from django.db.models import F

from .forms import AssignmentCreateForm, AssignmentSubmissionForm
from .models import Assignment, AssignmentSubmission
from authentication.models import Account
from courses.models import Course


# Create assignment view
@login_required
def AssignmentCreateView(request, id=None):
    if request.user.type == 'Teacher':
        if request.POST:
            form = AssignmentCreateForm(request.POST)
            if form.is_valid():
                assignment = form.save(commit=False)
                assignment_change = "created"
                if request.POST['create-assignment'] != "None":
                    assignment.id = request.POST['create-assignment']
                    assignment_change = "updated"
                assignment.user = Account.objects.get(username=request.user.username)
                assignment.save()
                messages.success(
                    request, f'Your assignment has been {assignment_change} successfully!')

                return redirect('assignments:home')
        else:
            template = loader.get_template(
                'assignments/assignment_create.html')
            form = AssignmentCreateForm()
            if id is not None:
                assignment = Assignment.objects.get(id=id)
                form = AssignmentCreateForm(
                    initial={
                        'title': assignment.title,
                        'content': assignment.content,
                        'course': assignment.course,
                        'marks': assignment.marks,
                        'deadline': assignment.deadline.date().isoformat()
                    }
                )
            context = {
                'create_form': form,
                'id': id
            }
            return HttpResponse(template.render(context, request))
    else:
        messages.warning(request, f'You are not authorised to create assignments!')
        return redirect('assignments:home')


# Assignment list view
@login_required
def AssignmentView(request):
    if request.method == 'POST':
        if 'delete-assignment' in request.POST:
            Assignment.objects.filter(id=request.POST['delete-assignment']).delete()
            # os.remove(f"{settings.BASE_DIR}{AssignmentSubmission.objects.get(assignment__id=request.POST['delete-assignment']).file.url}")
        return redirect('assignments:home')
    else:
        events = list(Assignment.objects.filter().values().all())
        event_data = get_deadlines(events)
        if request.user.type == 'Student':
            assignments = Assignment.objects.filter(course__id__in=request.user.enrolled_courses).values().all()
            submissions = list(AssignmentSubmission.objects.filter(
                user__username=request.user.username).values_list('assignment__id', flat=True))
        else:
            assignments = Assignment.objects.filter(user=Account.objects.get(username=request.user.username)).all()
            submissions = None
        context = {
            'assignments': assignments,
            'submissions': submissions,
            'event_data': json.dumps(event_data),
            'type': 'assignments'
        }
        template = loader.get_template('assignments/assignments.html')
        return HttpResponse(template.render(context, request))


# Assignment submission view for student
@login_required
def AssignmentSubmissionView(request, id):
    if request.user.type == 'Student':
        if request.POST:
            form = AssignmentSubmissionForm(request.POST, request.FILES)
            if form.is_valid():
                if AssignmentSubmission.objects.filter(assignment=Assignment.objects.get(id=id), user=Account.objects.get(username=request.user.username)).all().count() > 0:
                    os.remove(
                        f'{settings.BASE_DIR}{AssignmentSubmission.objects.get(assignment=Assignment.objects.get(id=id), user=Account.objects.get(username=request.user.username)).file.url}')
                    AssignmentSubmission.objects.filter(
                        assignment=Assignment.objects.get(id=id),
                        user=Account.objects.get(
                            username=request.user.username)
                    ).delete()
                    credit_account = Account.objects.get(username=request.user.username)
                    credit_account.forum_credits = F('assignment_credits') - 1
                    credit_account.save()
                else:
                    credit_account = Account.objects.get(username=request.user.username)
                    credit_account.forum_credits = F('assignment_credits') + 1
                    credit_account.save()
                submit = AssignmentSubmission(file=request.FILES['file'], user=Account.objects.get(
                    username=request.user.username), assignment=Assignment.objects.get(id=id))
                submit.save()
                messages.success(
                    request, f'Your assignment has been submitted!')

                return redirect('assignments:home')

        else:
            template = loader.get_template(
                'assignments/assignment_submission.html')
            form = AssignmentSubmissionForm()
            context = {
                'create_form': form
            }
            return HttpResponse(template.render(context, request))
    else:
        return redirect('assignments:home')


# Submitted assignment view for teacher
@login_required
def SubmittedAssignment(request, id):
    if request.method == 'POST':
        os.remove(f'{settings.BASE_DIR}{AssignmentSubmission.objects.get(assignment=Assignment.objects.get(id=id), user=Account.objects.get(username=request.user.username)).file.url}')
        AssignmentSubmission.objects.filter(assignment=Assignment.objects.get(id=id), user=Account.objects.get(username=request.user.username)).delete()
        return redirect('assignments:home')
    else:
        submission = AssignmentSubmission.objects.filter(
            assignment__id=id, user__username=request.user.username).all()
        submission = submission[len(submission) - 1]
        context = {
            'submission': submission
        }
        template = loader.get_template('assignments/assignment_submitted.html')
        return HttpResponse(template.render(context, request))


# Assignment submission list view
@login_required
def AssignmentSubmissionListView(request, id):
    if request.method == 'POST':
        grade = AssignmentSubmission.objects.get(assignment__id=id, user__username=request.POST['student'])
        grade.marks = request.POST['grade']
        grade.save()
        messages.success(request, f"{Account.objects.get(username=request.POST['student'])}'s assignment has been graded!")
        return redirect('assignments:submissions', id)
    else:
        assignment = Assignment.objects.get(id=id)
        submissions = AssignmentSubmission.objects.filter(assignment=assignment).all()
        template = loader.get_template('assignments/assignment_submission_list.html')
        ticks = range(0, assignment.marks + 1, int(assignment.marks/10))
        context = {
            'assignment': assignment,
            'submissions': submissions,
            'ticks': ticks
        }
        return HttpResponse(template.render(context, request))

# Assignment submission deadlines
def get_deadlines(assignments):
    assignment_list = []
    for assignment in assignments:
        assignment_list.append({
            'name': assignment['title'],
            'description': assignment['content'],
            'club': Course.objects.get(id=assignment['course_id']).name,
            'year': assignment['deadline'].year,
            'month': assignment['deadline'].month,
            'day': assignment['deadline'].day,
            'hour': assignment['deadline'].hour,
            'minute': assignment['deadline'].minute,
            'duration': None,
        })
    return {
        'events': assignment_list
    }

assignments/templates/assignments/assignment_create.html
{% extends 'base.html' %}
{% load tz %}
{% load static %}

{% block title %} Assignment Create {% endblock %}

{% block content %}

<a class="h6 mb-5 text-gray-800" href="{% url 'assignments:home' %}">
    Assignments
</a>
<i class="fa fa-angle-right fa-sm text-primary mx-1"></i>
<br><br>
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">
        Create Assignment
    </h1>
</div>

<div class="row">
    
    <div class="col-md-6">
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="title">
                    Assignment Title
                </label>
                <p>
                    {{ create_form.title }}
                </p>
                {% for error in create_form.title.errors %}
                    <p style="color:red;">
                        {{error}}
                    </p>
                {% endfor %}
            </div>
            <!--end form-group-->
            <div class="form-group">
                <label for="content">
                    Assignment
                </label>
                <p>
                    {{ create_form.content }}
                </p>
                {% for error in create_form.content.errors %}
                    <p style="color:red;">
                        {{error}}
                    </p>
                {% endfor %}
            </div>
            <!--end form-group-->
            <div class="form-group">
                <label for="content">
                    Course
                </label>
                <p>
                    {{ create_form.course }}
                </p>
                {% for error in create_form.content.errors %}
                    <p style="color:red;">
                        {{error}}
                    </p>
                {% endfor %}
            </div>
            <!--end form-group-->
            <div class="form-group">
                <label for="marks">
                    Marks
                </label>
                <p>
                    {{ create_form.marks }}
                </p>
                {% for error in create_form.marks.errors %}
                    <p style="color:red;">
                        {{error}}
                    </p>
                {% endfor %}
            </div>
            <!--end form-group-->
            {% localtime on %}
                <div class="form-group">
                    <label for="duration">
                        Deadline
                    </label>
                    <p>
                        {{ create_form.deadline }}
                    </p>
                    {% for error in create_form.deadline.errors %}
                        <p style="color:red;">
                            {{error}}
                        </p>
                    {% endfor %}
                </div>
                <!--end form-group-->
            {% endlocaltime %}
            <div class="form-group mb-0 row">
                <div class="col-12 mt-2">
                    <button class="btn btn-primary  btn-block waves-effect waves-light" type="submit" name="create-assignment" value="{{ id }}">
                        Create Assignment
                    </button>
                </div>
            </div>
            <!--end form-group-->
        </form>
    </div>
    <div class="col-xl-4 col-lg-5">
        <div class="card shadow py-4 d-sm-flex align-items-center justify-content-between mb-4">
            <h5 class="mx-5 py-3">
                Remember, each assignment submission can earn you credits!
            </h5>
            <img class="card-img-top mx-auto d-block p-5" src="{% static 'undraw_detailed_analysis_re_tk6j.svg' %}" alt="an image">
        </div>    
    </div>
</div>

<script>
    var val = "{{ user.username }}"
    var sel = document.getElementById('id_user');
    var opts = sel.options;
    for (var j = 0; j < opts.length; j++) {
        console.log(opts[j]);
        if (opts[j].value === val) {
            sel.selectedIndex = j;
            break;
        }
    }
</script>

{% endblock %}

assignments/templates/assignments/assignment_submission.html
{% extends 'base.html' %}

{% block title %} 
    Assignment Submission 
{% endblock %}

{% block content %}

<a class="h6 mb-5 text-gray-800" href="{% url 'assignments:home' %}">
  Assignments
</a>

<i class="fa fa-angle-right fa-sm text-primary mx-1"></i>
<br /><br />
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Submit Assignment</h1>
</div>
<div class="col-md-6">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group input-group mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text">Upload</span>
      </div>
      <p class="custom-file">
        <label class="custom-file-label" for="file">Choose file</label>
        {{ create_form.file }}
      </p>
      {% for error in create_form.file.errors %}
      <p style="color: red">{{error}}</p>
      {% endfor %}
    </div>
    <div class="form-group mb-0 row">
      <div class="col-12 mt-2">
        <button
          class="btn btn-primary btn-block waves-effect waves-light"
          type="submit"
        >
          Submit Assignment
        </button>
      </div>
    </div>
  </form>
</div>

{% endblock %}

assignments/templates/assignments/assignment_submission_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Assignments
{% endblock %}


{% block content %}
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div style="color:red;">
                    {{ message|safe }}
                </div>
            {% else %}
                <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">
                    {{ message|safe }}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    <a class="h6 mb-5 text-gray-800" href="{% url 'assignments:home' %}">
        Assignments
    </a>
    <i class="fa fa-angle-right fa-sm text-primary mx-1"></i>
    <br><br>
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">
            {{ assignment.name|title }} Submissions
        </h1>
    </div>
    <div class="col-xl-8 col-lg-7">
        <!-- Card Header - Dropdown -->
        {% for submission in submissions %}
            <div class="card shadow mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h5 class="m-0 font-weight-bold text-primary">
                        {{submission.user|title}}
                    </h5>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <a href="{{ submission.file.url }}" download="">{{ submission.file.name|slice:'12:' }}</a>
                </div>
                <div class="card-footer py-3">
                    {% if submission.marks is None %}
                        <form method="post" class="d-flex flex-row align-items-center justify-content-between">
                            {% csrf_token %}
                            <div class="input-group col-3">
                                <div class="input-group-prepend">
                                    <label class="input-group-text" for="grade">Marks</label>
                                </div>
                                <input type="text" name="student" value="{{ submission.user.username }}" hidden>
                                <input type="number" class="form-control" id="grade" name="grade" min=0 max={{ assignment.marks }} step=1 value=0>
                            </div>
                            <div class="" style="width: fit-content">
                                <button class="btn btn-outline-primary mx-4" type="submit">
                                    Submit
                                </button>
                            </div>
                        </form>
                    {% else %}
                        <div class="d-flex flex-row align-items-center justify-content-between">
                            <div>
                                Marks: {{ submission.marks }}
                            </div>
                            <div>
                                <button class="btn btn-outline-primary mx-4" type="submit" disabled>
                                    Graded
                                </button>
                            </div>
                        </div>
                    {% endif %}

                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

assignments/templates/assignments/assignment_submitted.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Assignments
{% endblock %}


{% block content %}
<a class="h6 mb-5 text-gray-800" href="{% url 'assignments:home' %}">
    Assignments
</a>
<i class="fa fa-angle-right fa-sm text-primary mx-1"></i>
<br><br>
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">
            Submitted Assignment
        </h1>
    </div>
    <div class="col-xl-8 col-lg-7">
        <div class="card shadow mb-4">
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                {{ submission.assignment.title }}
                <form action="" method="post">
                {% csrf_token %}
                    <button class="btn btn-outline-danger" type="submit" name="delete-submission" value="{{ submission.assignment.id }}">
                        Delete Assignment
                    </button>
                </form>
            </div>
            <div class="card-body">
                <p>
                    {{ submission.assignment.content }}
                </p>
                <p>
                    {{ submission.assignment.marks }} Mark{{ submission.assignment.marks|pluralize }}
                </p>

            </div>
            <div class="card-footer py-3 d-flex flex-row align-items-center justify-content-between">
                {{ submission.assignment.deadline }}
                <a href="{% url 'assignments:submit' submission.assignment.id|slugify %}" class="btn btn-outline-primary">
                    Re-Submit Assignment
                </a>
            </div>
        </div>
    </div>
{% endblock %}

assignments/templates/assignments/assignments.html
{% extends 'base.html' %}
{% load static %}
{% load days_until %}
{% block title %}
    Assignments
{% endblock %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div style="color:red;">
                    {{ message|safe }}
                </div>
            {% else %}
                <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">
                    {{ message|safe }}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">
        Assignments
    </h1>
    {% if request.user.type == 'Teacher' %}
        <a href="{% url 'assignments:create' %}" class="btn btn-primary">
            Create an Assignment
        </a>
    {% endif %}
</div>
<div class="row">
    <div class="col-xl-8 col-lg-7">
        <!-- Card Header - Dropdown -->
        {% for assignment in assignments %}
            <div class="card shadow mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between assignment-{{ assignment.id }}">
                    <h5 class="m-0 font-weight-bold text-primary">
                        {{assignment.title}}
                    </h5>
                    {% if request.user.type == 'Teacher' %}
                        <div class="dropdown no-arrow">
                            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-ellipsis-v fa-lg text-primary"></i>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                                aria-labelledby="dropdownMenuLink">
                                <a class="dropdown-item" href="{% url 'assignments:create' assignment.id|slugify %}">
                                    Edit Assignment
                                </a>
                                <form action="" method="post">
                                    {% csrf_token %}
                                    <button class="dropdown-item" type="submit" name="delete-assignment" value="{{ assignment.id }}">
                                        Delete Assignment
                                    </button>
                                </form>
                            </div>
                        </div>
                    {% endif %}
                </div>
                
                <!-- Card Body -->
                <div class="card-body assignment-{{ assignment.id }}">
                    <p>{{assignment.content}} </p>
                    <p>{{assignment.marks}} Mark{{assignment.marks|pluralize}} </p>
                </div>
                
                <div class="card-footer d-flex flex-row align-items-center justify-content-between assignment-{{ assignment.id }}">
                    <div>
                        <span>
                            {{assignment.deadline|date}}
                        </span>
                        <br>
                        {% if assignment.deadline|days_until > 3 %}
                            <span>{{ assignment.deadline|days_until }} day{{ assignment.deadline|days_until|pluralize }} to go</span>
                        {% elif assignment.deadline|days_until > 0 %}
                            <span class="text-danger">{{ assignment.deadline|days_until }} day{{ assignment.deadline|days_until|pluralize }} to go</span>
                        {% endif %}
                    </div>
                    {% if request.user.type == 'Student' %}
                        {% if assignment.deadline|days_until > 0 %}
                            {% if assignment.id in submissions %}
                                <a href="{% url 'assignments:submit-view' assignment.id|slugify %}" class="btn btn-outline-primary">
                                    View Submitted Assignment
                                </a>
                            {% else %}
                                <a href="{% url 'assignments:submit' assignment.id|slugify %}" class="btn btn-outline-primary">
                                    Submit Assignment
                                </a>
                            {% endif %}
                        {% else %}
                            <button class="btn btn-outline-danger" disabled>
                                Deadline Passed
                            </button>
                        {% endif %}
                    {% else %}
                        <a href="{% url 'assignments:submissions' assignment.id|slugify %}" class="btn btn-outline-primary">
                            View Submissions
                        </a>
                    {% endif %}

                </div>
            </div>
        {% endfor %}
    </div>
    <div class="col-xl-4 col-lg-5">
        <div class="card shadow py-4 d-sm-flex align-items-center justify-content-between mb-4">
            <h5 class="mx-5 py-3">
                Remember, each assignment submission can earn you credits
            </h5>
            <img class="card-img-top mx-auto d-block p-2" src="{% static 'undraw_notebook_re_id0r.svg' %}" alt="an image">
        </div>
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">
                Deadlines
            </h1>
        </div>
        {% include 'clubs/events_calendar.html' %}
    </div>
</div>
{% endblock %}

assignments/templates/assignments/create_assignment_template.html
<div class="assignment-{{ assignment.id }}-form">
  <form method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label for="title"> Assignment Title </label>
      <p>{{ create_form.title }}</p>
      {% for error in create_form.title.errors %}
      <p style="color: red">{{error}}</p>
      {% endfor %}
    </div>
    <!--end form-group-->
    <div class="form-group">
      <label for="content"> Assignment </label>
      <p>{{ create_form.content }}</p>
      {% for error in create_form.content.errors %}
      <p style="color: red">{{error}}</p>
      {% endfor %}
    </div>
    <!--end form-group-->
    <div class="form-group">
      <label for="content"> Course </label>
      <p>{{ create_form.course }}</p>
      {% for error in create_form.content.errors %}
      <p style="color: red">{{error}}</p>
      {% endfor %}
    </div>
    <!--end form-group-->
    <div class="form-group">
      <label for="marks"> Marks </label>
      <p>{{ create_form.marks }}</p>
      {% for error in create_form.marks.errors %}
      <p style="color: red">{{error}}</p>
      {% endfor %}
    </div>
    <!--end form-group-->
    {% localtime on %}
    <div class="form-group">
      <label for="duration"> Deadline </label>
      <p>{{ create_form.deadline }}</p>
      {% for error in create_form.deadline.errors %}
      <p style="color: red">{{error}}</p>
      {% endfor %}
    </div>
    {% endlocaltime %}
    <div class="form-group mb-0 row">
      <div class="col-12 mt-2">
        <button 
          class="btn btn-primary btn-block waves-effect waves-light"
          type="submit"
        >
          Create Assignment
        </button>
      </div>
    </div>
  </form>
</div>