Studee/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
import authentication.views as views


urlpatterns = [
    path('', include('authentication.urls', namespace='authentication')),
    path('admin/', admin.site.urls),
    path('forum/', include('forum.urls', namespace='forum')),
    path('scheduler/', include('scheduler.urls', namespace='scheduler')),
    path('assignments/', include('assignments.urls', namespace='assignments')),
    path('courses/', include('courses.urls', namespace='courses')),
    path('clubs/', include('clubs.urls', namespace='clubs')),
    path('tinymce/', include('tinymce.urls')),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),
    path('account_settings/', views.accountSettings, name='account_settings'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='authentication/changePassword.html'),
         name='password_change'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_change.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    path('password_change/done/', views.password_change_done, name='password_change_done'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
from django.urls import path
from . import views
from .views import *


app_name = "authentication"

urlpatterns = [
    path('home/', views.homePage, name='home'),
    path('', views.landingPage, name='landing'),
    path('register/', views.register, name='register'),
    path('accounts/login/', views.loginView, name='login'),
    path('profile/', views.profile, name='profile'),
    path('editProfile/', views.editProfile, name='editProfile'),
    path('logout/', views.logout_view, name='logout'),
    path('deleteuser/', views.deleteuser, name='deleteuser')
]

clubs/urls.py
from django.http import request
from django.urls import path
from django.conf.urls import url
from .views import *

app_name = "clubs"

urlpatterns = [
    path("", home, name="home"),
    url(r"create_event/(?P<slug>[\w-]+)/$", create_event, name="create_event"),
    url(r"(?P<slug>[\w-]+)/$", club_view, name="club"),
    path("create_club", create_club, name="create_club"),
    path("approve_member", approve_member, name="approve_member"),
]

#handler404 = 'main.views.error404'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Studee</title>

    <!-- Custom fonts for this template-->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jarallax/1.12.8/jarallax.min.js" integrity="sha512-ieMvcpXFcmaKJukz4J6H3C/jNUU6S1UUPDuAHiyk3Vxx8NEnKbGu+r3fGtK8+2D7Im1+ASmHCyPE0mRGL1rdaA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jarallax/1.12.8/jarallax-video.min.js" integrity="sha512-gFcUTdQpdNIemLZK51GuahUFfhRmkOgE5Ckoj5MeONAXkOGlDxDARgWAehiVFby3RhNsfiVxwIKf2w0eQRPRpA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js" integrity="sha512-Eak/29OTpb36LLo2r47IpVzPBLXnAMPAVypbSZiZ4Qkf8p/7S/XRG5xp7OKWPPYfJT6metI+IORkR5G8F900+g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    
    <link rel="shortcut icon" href="{% static 'Favicon.png' %}" type="image/x-icon"> 
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/default-assets/active.js' %}"></script>
    <style>
        a:hover {
            text-decoration: none;
        }
        .user-image, .user-image-edit {
            height : 100px;
            width: 100px;
            margin-left: auto;
            margin-right: auto;
        }
        .edit-photo {
            position: relative;
            top: -100px;
            width: 100px;
            height: 100px;
            text-align: center;
            align-items: center;
            margin-left: inherit;
            margin-right: inherit;
            background-color: rgba(145, 145, 145, 0.2);
            border-radius: inherit;
            opacity: 0;
            animation-timing-function: ease-in;
            animation-duration: 1s;
            cursor: pointer;
        }
        .edit-photo-icon {
            color: #ffffff;
            margin-top: 38px;
        }

        .edit-photo:hover {
            opacity: 1;
        }

        .user-image-class{
            text-align: center;
            align-items: center;
            height: 100px;
        }

        .profile-card {
            padding: 2rem;
            margin-top: 2rem;
        }

        .user-information {
            padding-left: 2rem;
        }

        .user-details, .profile-header {
            font-size: 0.9rem;
            color: #898989;
        }

        .header {
            font-size: 1.5rem;
            font-weight: bold;
            margin-top: 0.5rem;
            margin-bottom: 0.5rem;
        }
    </style>
</head>
<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
        {% include 'sidebar.html' %}
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">
                {% include 'topbar.html' %}
                <!-- Begin Page Content -->
                <div class="container-fluid" style="min-height: 100vh">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; All rights reserved | Studee | Engage <script>document.write(new Date().getFullYear());</script></span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Model-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="{% url 'authentication:logout' %}">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>

</body>

</html>

templates/landing.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Title -->
  <title>Studee</title>

  <!-- Favicon -->
  <link rel="shortcut icon" href="{% static 'Favicon.png' %}" type="image/x-icon">

  <!-- Core Stylesheet -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


    {% block styles %} {% endblock %}

  <!-- ******* All JS ******* -->
  <!-- jQuery js -->

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jarallax/1.12.8/jarallax.min.js" integrity="sha512-ieMvcpXFcmaKJukz4J6H3C/jNUU6S1UUPDuAHiyk3Vxx8NEnKbGu+r3fGtK8+2D7Im1+ASmHCyPE0mRGL1rdaA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jarallax/1.12.8/jarallax-video.min.js" integrity="sha512-gFcUTdQpdNIemLZK51GuahUFfhRmkOgE5Ckoj5MeONAXkOGlDxDARgWAehiVFby3RhNsfiVxwIKf2w0eQRPRpA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js" integrity="sha512-Eak/29OTpb36LLo2r47IpVzPBLXnAMPAVypbSZiZ4Qkf8p/7S/XRG5xp7OKWPPYfJT6metI+IORkR5G8F900+g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.min.js" integrity="sha512-9CWGXFSJ+/X0LWzSRCZFsOPhSfm6jbnL+Mpqo0o8Ke2SYr8rCTqb4/wGm+9n13HtDE1NQpAEOrMecDZw4FXQGg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>


    <!-- Active js -->
    <script src="{% static 'js/default-assets/active.js' %}"></script>
    <style>
        .carousel-item {
            background: no-repeat center center scroll;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }
        .navbar {
            position: absolute;
            z-index: 10;
            width: 100%;
        }
        .background1 {
            background-image: url('/static/Landing-page.png');
            background-size: contain;
            background-repeat: no-repeat;
            background-position: center;
            background-attachment: scroll;
            background-size: cover;
            min-height: 100vh;
        }
        .background2 {
            background-image: url('/static/Landing-page(2).png');
            background-size: contain;
            background-repeat: no-repeat;
            background-position: center;
            min-height: 100vh;
        }
    </style>
</head>

<body style="min-height: 100vh">
    {% include 'nav.html' %}

    <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner bg-info" role="listbox">
        <div class="carousel-item min-vh-100 active" style="background-image: url('/static/Landing-page.png')">
        </div>
        <div class="carousel-item min-vh-100" style="background-image: url('/static/Landing-page(2).png')">
        </div>
      </div>
        <a class="carousel-control-prev" href="#carouselExampleSlidesOnly" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleSlidesOnly" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
     <!-- Footer -->
     <footer class="sticky-footer bg-white fixed-bottom" style="background-color: transparent!important">
      <div class="container my-auto" style="background-color: transparent">
          <div class="copyright text-center my-auto">
              <span>Copyright &copy; All rights reserved | Studee | <script>document.write(new Date().getFullYear());</script></span>
          </div>
      </div>
  </footer>
  <!-- End of Footer -->

</body>
</html>

templates/nav.html
{% load static %}
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/default-assets/active.js' %}"></script>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container px-4 px-lg-5 my-0">
        <a class="navbar-brand" href="#page-top">Studee</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto my-0">
                
                <li class="nav-item"><a class="nav-link" href="{% url 'authentication:login' %}">Login</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'authentication:register' %}">Sign Up</a></li>
     
            </ul>
        </div>
    </div>
</nav>


  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

templates/sidebar.html
{% load static %}
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'authentication:home' %}">
        <div class="sidebar-brand-icon">
            <img src="{% static 'Logo.png' %}" width="28"/>
        </div>
        <div class="sidebar-brand-text mx-3">Studee</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'authentication:home' %}">
            <i class="fas fa-fw fa-university"></i>
            <span>
                Home
            </span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <li class="nav-item active">
        <a class="nav-link" href="{% url 'courses:home' %}">
            <i class="fas fa-fw fa-chalkboard-teacher"></i>
            <span>
                Courses
            </span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'assignments:home' %}">
            <i class="fas fa-fw fa-clipboard-list"></i>
            <span>Assignments</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <li class="nav-item active">
        <a class="nav-link" href="{% url 'forum:home' %}">
            <i class="fas fa-fw fa-users"></i>
            <span>
                Forum
            </span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <li class="nav-item active">
        <a class="nav-link" href="{% url 'scheduler:home' %}">
            <i class="fas fa-fw fa-syringe"></i>
            <span>
                Vaccination Tracker
            </span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <li class="nav-item active">
        <a class="nav-link" href="{% url 'clubs:home' %}">
            <i class="fas fa-fw fa-theater-masks"></i>
            <span>
                Clubs
            </span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>

templates/topbar.html
{% load static %}
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    
    <!-- Sidebar Toggle (Topbar) -->
    
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Search -->
    <p>
        <br/>
    <h5 class="m-0 font-weight-bold text-primary"><b>Committed To Lifelong Learning In A Caring Environment</b></h5>
    </p>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small"
                            placeholder="Search for..." aria-label="Search"
                            aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Nav Item - Alerts -->
        {% if request.user.type == 'Teacher' %}
            <li class="nav-item dropdown no-arrow mx-1">
                <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user-check fa-fw"></i>
                    <!-- Counter - Alerts -->
                    <span class="badge badge-danger badge-counter">{{ request.user.club_approvals|length }}</span>
                </a>
                <!-- Dropdown - Alerts -->
                <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                    aria-labelledby="alertsDropdown">
                    <h6 class="dropdown-header">
                        Club Approval Requests
                    </h6>
                    {% for club_approval in request.user.club_approvals %}
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="mr-3">
                                <div class="icon-circle bg-primary">
                                    <i class="fas fa-file-alt text-white"></i>
                                </div>
                            </div>
                            <div>
                                <div class="small text-gray-500">{{ club_approval.club.name }}</div>
                                <span class="font-weight-bold">{{ club_approval.member|title }}</span>
                                <form method="post" action="{% url 'clubs:approve_member' %}">
                                    {% csrf_token %}
                                    <button class="btn btn-outline-primary" type="submit" name="approve-member" value="{{ club_approval.club.slug }}_{{ club_approval.member.username }}">
                                        Approve
                                    </button>
                                </form>

                            </div>
                        </a>
                    {% endfor %}


                </div>
            </li>
        {% endif %}

{##}
{#        <!-- Nav Item - Messages -->#}
{#        <li class="nav-item dropdown no-arrow mx-1">#}
{#            <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button"#}
{#                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#                <i class="fas fa-envelope fa-fw"></i>#}
{#                <!-- Counter - Messages -->#}
{#                <span class="badge badge-danger badge-counter">7</span>#}
{#            </a>#}
{#            <!-- Dropdown - Messages -->#}
{#            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"#}
{#                aria-labelledby="messagesDropdown">#}
{#                <h6 class="dropdown-header">#}
{#                    Message Center#}
{#                </h6>#}
{#                <a class="dropdown-item d-flex align-items-center" href="#">#}
{#                    <div class="dropdown-list-image mr-3">#}
{#                        <img class="rounded-circle" src="{% static 'img/undraw_profile_1.svg' %}"#}
{#                            alt="...">#}
{#                        <div class="status-indicator bg-success"></div>#}
{#                    </div>#}
{#                    <div class="font-weight-bold">#}
{#                        <div class="text-truncate">Hi there! I am wondering if you can help me with a#}
{#                            problem I've been having.</div>#}
{#                        <div class="small text-gray-500">Emily Fowler · 58m</div>#}
{#                    </div>#}
{#                </a>#}
{##}
{#                <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>#}
{#            </div>#}
{#        </li>#}

        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ request.user|title }}</span>
                <img class="img-profile rounded-circle" src="{{ request.user.profile_pic.url }}">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'authentication:profile' %}">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profile
                </a>
                <a class="dropdown-item" href="{% url 'account_settings' %}">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    Settings
                </a>
{#                <a class="dropdown-item" href="{% url 'authentication:activity_log' %}">#}
{#                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>#}
{#                    Activity Log#}
{#                </a>#}
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
            </div>
        </li>

    </ul>

</nav>